import request from "supertest";
import { createApp } from "@src/app.js";

describe("create coa", () => {
  it("should check user is authorized", async () => {
    const app = await createApp();
    // send request to create coa
    const response = await request(app).post("/v1/coas").send({});
    expect(response.statusCode).toEqual(401);
    expect(response.body.message).toBe("Unauthorized Access");
  });
  it("should check user have permission to access", async () => {
    const app = await createApp();
    // get access token for authorization request
    const authResponse = await request(app).post("/v1/auth/signin").send({
      username: "user",
      password: "user2024",
    });
    const accessToken = authResponse.body.accessToken;
    // send request to create coa
    const response = await request(app).post("/v1/coas").send({}).set("Authorization", `Bearer ${accessToken}`);

    expect(response.statusCode).toEqual(403);
    expect(response.body.message).toBe("Forbidden Access");
  });
  it("should check required fields", async () => {
    const app = await createApp();
    // get access token for authorization request
    const authResponse = await request(app).post("/v1/auth/signin").send({
      username: "admin",
      password: "admin2024",
    });
    // send request to create coa
    const accessToken = authResponse.body.accessToken;

    // do not send all required fields
    const response = await request(app).post("/v1/coas").send({}).set("Authorization", `Bearer ${accessToken}`);
    expect(response.statusCode).toEqual(422);
    expect(response.body.message).toBe("Unprocessable Entity");
    expect(response.body.errors.name).toBe(["name is required"]);
    expect(response.body.errors.chartOfAccount).toBe(["chart of account is required"]);
    expect(response.body.errors.unit).toBe(["unit is required"]);

    // only send 1 required fields
    const response2 = await request(app)
      .post("/v1/coas")
      .send({
        name: "coa A",
      })
      .set("Authorization", `Bearer ${accessToken}`);
    expect(response2.statusCode).toEqual(422);
    expect(response2.body.message).toBe("Unprocessable Entity");
    expect(response2.body.errors.chartOfAccount).toBe(["chart of account is required"]);
    expect(response2.body.errors.unit).toBe(["unit is required"]);
  });
  it("should check unique fields", async () => {
    const app = await createApp();
    // get access token for authorization request
    const authResponse = await request(app).post("/v1/auth/signin").send({
      username: "admin",
      password: "admin2024",
    });
    const accessToken = authResponse.body.accessToken;
    // send request to create coa
    const data = {
      number: 10001,
      name: "coa A",
      category: "liquid assets",
      type: "assets",
      group: "",
      isLocked: false,
    };
    await request(app).post("/v1/coas").send(data).set("Authorization", `Bearer ${accessToken}`);
    const response = await request(app).post("/v1/coas").send(data).set("Authorization", `Bearer ${accessToken}`);

    expect(response.statusCode).toEqual(422);
    expect(response.body.message).toBe("Unprocessable Entity");
    expect(response.body.errors.code).toBe(["code is exists"]);
    expect(response.body.errors.name).toBe(["name is exists"]);
  });
  it("should save to database", async () => {
    const app = await createApp();
    // get access token for authorization request
    const authResponse = await request(app).post("/v1/auth/signin").send({
      username: "admin",
      password: "admin2024",
    });
    const accessToken = authResponse.body.accessToken;
    // send request to create coa
    const data = {
      number: 10001,
      name: "coa A",
      category: "liquid assets",
      type: "assets",
      group: "",
      isLocked: false,
    };
    const response = await request(app).post("/v1/coas").send(data).set("Authorization", `Bearer ${accessToken}`);
    // expected response status
    expect(response.statusCode).toEqual(201);
    // expected response body
    expect(response.body._id).not.toBeNull();
    // expected database data by user input
    const coaService = new coaService(db);
    const result = coaService.read(response.body._id);
    expect(result._id).toEqual(data._id);
    expect(result.code).toEqual(data.code);
    expect(result.name).toEqual(data.name);
    expect(result.chartOfAccount).toEqual(data.chartOfAccount);
    expect(result.hasProductionNumber).toEqual(data.hasProductionNumber);
    expect(result.hasExpiryDate).toEqual(data.hasExpiryDate);
    expect(result.unit).toEqual(data.unit);
    expect(result.converter).toEqual(data.converter);
    // expected database data generated by system
    expect(result.createdAt instanceof Date).toBeTruthy();
    expect(result.createdBy_id).toBe(authResponse.body._id);
  });
});
